[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"

[phases.setup]
aptPkgs = ["nodejs", "npm"]

[phases.build]
cmds = [
  "npm install --production=false",
  "npm run build"
]

[phases.deploy]
cmd = "npm run start:prod"

[nixpacks]
node-memory = "2048" 